version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      # - mkdir -p build
      # - pip install -r requirements.txt -t build/
      # - zip -r my_python_code.zip build
      
  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover
  
  post_build:
    commands:
      # 빌드 결과물을 S3 버킷에 업로드
      - aws s3 cp ./ s3://codepipelinecdkstack-mypipelineartifactsbucket727-1e6m3gc2l2wz6/ --recursive

artifacts:
  files:
    - '**/*'
