version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover
  
  post_build:
    commands:
      # 빌드 결과물을 S3 버킷에 업로드
      - aws s3 cp ./ s3://codepipeline-artifact-bucket-lambda/ --recursive

artifacts:
  files:
    - '**/*'
